import Products from "../components/Products";
import Link from "next/link";

export const metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

const fetchData = () => {
  const result = fetch("https://dummyjson.com/products").then((res) =>
    res.json()
  );
  return result;
};

export default async function HomeProducts() {
  const { products } = await fetchData();
  return (
    <>
      <Products products={products} />
      <div className="w-full h-20 flex justify-center transition-all ease-in-out duration-300 hover:scale-110 items-center">
        <Link
          href={"/shop"}
          className="w-28 h-12 bg-sky-700 hover:bg-sky-500 transition-all ease-in-out duration-300 rounded-xl text-white border-l flex justify-center items-center "
        >
          See All
        </Link>
      </div>
    </>
  );
}
