import Products from "../components/Products";
import Search from "../components/Search";

export const metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

const fetchData = () => {
  const result = fetch("https://dummyjson.com/products?limit=0").then((res) =>
    res.json()
  );
  return result;
};

export default async function Shop() {
  const { products } = await fetchData();
  return (
    <>
      <Search />
      <Products products={products} />
    </>
  );
}
